### ISSUE TITLE
Upgrade from 3.9.1 to 3.9.4 breaks my tests

### ISSUE THREAD

**Issue by fr0** [NetanelBasal/spectator#127] opened 2019-06-28 15:11 UTC
There are two sets of failures popping up in 3.9.4 that passed in 3.9.1:

```
TypeError: el.getClientRects is not a function
    at <Jasmine>
    at isHidden (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@netbasal/spectator/fesm2015/netbasal-spectator.js:1138:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@netbasal/spectator/fesm2015/netbasal-spectator.js:1194:1
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/library/controls/loading-indicator.component.spec.ts:187:32)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/fake-async-test.js:605:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:359:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:129:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:358:1)
```

And

```
Expected element not to be visible
Error: Expected element not to be visible
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/library/controls/dialog.component.spec.ts:37:37)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:359:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:129:1)
```

Both issues are related to the `toBeVisible` helper.

**Comment by fr0** [comment] 2019-06-28 15:13
Probably caused by https://github.com/NetanelBasal/spectator/commit/fd7c9474e62f2d1cea4b7e93f5d06d86796c3374

**Comment by benelliott** [comment] 2019-06-28 15:15
Hi, this sounds like https://github.com/NetanelBasal/spectator/issues/122

Please could you double-check you have got v3.9.4 (e.g. by clearing out `node_modules/@netbasal` and reinstalling)?

**Comment by fr0** [comment] 2019-06-28 15:21
Thanks for the response.

I deleted my `yarn.lock` file and my `node_modules` folder, reinstalled, and the problem still happens.

**Comment by fr0** [comment] 2019-06-28 15:22
As mentioned in https://github.com/NetanelBasal/spectator/issues/122#issuecomment-505740308 --

```
In any case, in 3.9.1 the isVisible matcher works on elements not in the DOM. In 3.9.2+ it does not.
```

If this was intended, this is a breaking change and should've been published in a 4.0 release, not in a patch release.

**Comment by benelliott** [comment] 2019-06-28 15:24
I don't believe it was an intended behavioural change, but this is probably what's causing your issue. Is the element you are checking indeed removed from the DOM?

**Comment by NetanelBasal** [comment] 2019-06-28 15:26
So to re-support it, we need to add `if(!el) return true`.

**Comment by fr0** [comment] 2019-06-28 15:32
> I don't believe it was an intended behavioural change, but this is probably what's causing your issue. Is the element you are checking indeed removed from the DOM?

Yes, if I change the `.not.toBeVisible()` calls to `.not.toExist()`, the tests pass.

**Comment by LayZeeDK** [comment] 2019-07-02 08:19
I see that a fix has been merged but not published in a new version. How can OP try out the fix, @NetanelBasal?

**Comment by NetanelBasal** [comment] 2019-08-03 19:29
Released.

**Closed** 2019-08-03 19:29 UTC
Labels: regression
