### ISSUE TITLE
Bug: `el.getClientRects is not a function` on version 3.9.2

### ISSUE THREAD

**Issue by twjacobsen** [NetanelBasal/spectator#122] opened 2019-06-24 10:38 UTC
Hi,

I've just upgraded to 3.9.2, and I'm seeing this exception when using `isVisible()` matcher:

`el.getClientRects is not a function`.

Downgrading to 3.9.1 resolves the issue.
Using Headless Chrome (latest build), with Jasmine and Karma.

**Comment by benelliott** [comment] 2019-06-24 12:01
Hi, is `el` definitely a DOM element? Please could you post your spec code?

**Comment by twjacobsen** [comment] 2019-06-24 12:03
I haven't checked, but reading the tests, on 3.9.1 both `.toBeVisible()` and `.not.toBeVisible()` works as expected. The exact syntax is `expect('.class-selector').toBeVisible()`

**Comment by NetanelBasal** [comment] 2019-06-24 12:13
Maybe it's related to the new [implementation](https://github.com/NetanelBasal/spectator/blob/843c5dff226d37a0f78811bbdd294f62837d4f5c/projects/spectator/src/lib/matchers.ts#L250). Can you please share the code or reproduce on Stackblitz?

**Comment by twjacobsen** [comment] 2019-06-24 12:15
That was my assumption as well - got that assumption confirmed when downgrading. I'll try getting something reproduced on Stackblitz when I have some time.

**Comment by benelliott** [comment] 2019-06-24 12:18
It will be because the previous implementations passed your `expect` input through jQuery, which would convert a selector to an element before executing the check. The new implementation does not do this.

**Comment by benelliott** [comment] 2019-06-24 12:18
You can see this here:

https://github.com/NetanelBasal/spectator/commit/fd7c9474e62f2d1cea4b7e93f5d06d86796c3374#diff-c75eb71edd2ca39a6fdc949a98fa1dacL254

**Comment by NetanelBasal** [comment] 2019-06-24 12:19
Right. This was a breaking change we didn't take into account.

**Comment by benelliott** [comment] 2019-06-24 12:19
This is a regression since the documentation illustrates this kind of usage: https://netbasal.gitbook.io/spectator/api/matchers

**Comment by NetanelBasal** [comment] 2019-06-24 12:23
We should pass the argument through JQuery and use it.

**Comment by benelliott** [comment] 2019-06-24 12:23
I can push a quick fix for this.

**Comment by NetanelBasal** [comment] 2019-06-24 12:27
Thanks!

**Closed** 2019-06-24 12:55 UTC
Labels: regression

**Comment by benelliott** [comment] 2019-06-24 13:02
Should be available in 3.9.3

**Comment by benelliott** [comment] 2019-06-24 13:19
...Make that 3.9.4. Sorry @NetanelBasal, made a mistake during publish!

**Comment by NetanelBasal** [comment] 2019-06-24 13:19
No problem.

**Comment by twjacobsen** [comment] 2019-06-26 05:57
I just tried upgrading to 3.9.4 last night, and it was still not working. Sorry I haven't been able to find time to create a minimal repro. I'll get around to it, though.

**Comment by twjacobsen** [comment] 2019-06-26 06:23
Right, so I just had a thought. How does `isVisible` handle elements, that are not in the DOM at all? I haven't checked, but how should it work on an element with `*ngIf`?

**Comment by NetanelBasal** [comment] 2019-06-26 06:24
No, if you want to assert about ngIf, you should use `toExist`.

**Comment by twjacobsen** [comment] 2019-06-26 06:26
Yep, that's what I figured as well. But *should* `isVisible` support that? I mean, the fact it does not exist also means it's not visible ;)

**Comment by NetanelBasal** [comment] 2019-06-26 06:27
No, check [here](https://api.jquery.com/visible-selector/) what `isVisible` means.

**Comment by twjacobsen** [comment] 2019-06-26 06:35
According to those docs:

> Elements that are not in a document are considered hidden

Does that not mean, that elements that are removed with `*ngIf` will not be selected with the `:visible` selector?
